name: Generate documentation
on:  push
jobs:
  generate_documentation:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: windows-latest
    concurrency: gen-docs
    steps:
      - uses: actions/checkout@v2
      # - name: Add msbuild to PATH
      #   uses: microsoft/setup-msbuild@v1.1
      - name: Install DocFX
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install docfx
      - name: Generate documentation
        working-directory: docs
        run: docfx docfx.json
        continue-on-error: false
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          FOLDER: docs/_sit