name: Generate documentation
on:  push
jobs:
  generate_documentation:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-20.04
    concurrency: gen-docs
    steps:
      - uses: actions/checkout@v2
      - name: Generate documentation
        uses: nikeee/docfx-action@v1.0.0
        with:
          args: docs/docfx.json
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SINGLE_COMMIT: true
          FOLDER: docs/_site